/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorestaurante.Vistas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectorestaurante.Controlador.Bitacora;
import proyectorestaurante.Controlador.CheckPassword;
import proyectorestaurante.Modelo.conexion;
import proyectorestaurante.Modelo.Usuarios;


/**
 *
 * @author roger
 */
public class Login extends javax.swing.JFrame {

     
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblSesuon = new javax.swing.JLabel();
        jblUsuario = new javax.swing.JLabel();
        jtxUsuario = new javax.swing.JTextField();
        jblContraseña = new javax.swing.JLabel();
        jtxContraseña = new javax.swing.JTextField();
        jbtIngresar = new javax.swing.JButton();
        jbtRegistrarse = new javax.swing.JButton();
        jbContraseña = new javax.swing.JLabel();
        jcEmpleado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jblSesuon.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jblSesuon.setText("INICIO DE SESION");

        jblUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jblUsuario.setText("USUARIO");

        jtxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxUsuarioActionPerformed(evt);
            }
        });

        jblContraseña.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jblContraseña.setText("CONTRASEÑA");

        jtxContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxContraseñaActionPerformed(evt);
            }
        });

        jbtIngresar.setText("INGRESAR");
        jbtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIngresarActionPerformed(evt);
            }
        });

        jbtRegistrarse.setText("REGISTRARSE");
        jbtRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrarseActionPerformed(evt);
            }
        });

        jbContraseña.setText("OLVIDO LA CONTRASEÑA?");

        jcEmpleado.setText("Ingresar Como Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbContraseña)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jblSesuon))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jblUsuario)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblContraseña)
                            .addComponent(jtxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jbtIngresar)
                        .addGap(68, 68, 68)
                        .addComponent(jbtRegistrarse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jcEmpleado)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jblSesuon)
                .addGap(58, 58, 58)
                .addComponent(jblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jblContraseña)
                .addGap(34, 34, 34)
                .addComponent(jtxContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtIngresar)
                    .addComponent(jbtRegistrarse))
                .addGap(26, 26, 26)
                .addComponent(jcEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jbContraseña)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxUsuarioActionPerformed

    private void jtxContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxContraseñaActionPerformed

    private void jbtRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrarseActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jbtRegistrarseActionPerformed

    private void jbtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIngresarActionPerformed
        // TODO add your handling code here:
        
        String usuario = "";
        String pass = "";
        Bitacora dw = new Bitacora();
        try {
            CheckPassword verificar = new CheckPassword();
            char passArray[] = null;
          
            if (verificar.verificarPassword(passArray)) {
                String pas = new String(passArray);
                //creando objeto de conexion
                conexion con = new conexion();
                //consulta
                if(jcEmpleado.isSelected()){
                    con.setRs("SELECT ID_Empleado,Primer_Nom,Segundo_Nom,Primer_Ape,Segundo_Ape Email, Id_Usuario FROM dbrestaurante.empleados where Usuario ='" + jtxUsuario.getText() + "';");
                }
                else{
                    con.setRs("SELECT Id_Usuario, Usuario, Contraseña FROM dbrestaurante.usuarios where Usuarios ='" + jtxUsuario.getText() + "';");                    
                }
                //se obtienen los valores
                ResultSet valor = (ResultSet) con.GetRs();
                //Se mueve al unico registro devuelto
                if (valor.next()) {
                    usuario = valor.getString(2);
                    pass = valor.getString(3);
                    if (usuario.equals(jtxUsuario.getText()) && pass.equals(jtxContraseña.getText())) {
                        if(jcEmpleado.isSelected()){
                            OrdenesEmpleado op = new OrdenesEmpleado ();
                            op.setVisible(true);
                            dw.escribir(usuario + '\n' + pass);
                            dw.crearBitacora(usuario);
                            dispose();
                        }
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Error, usuario o contraseña no coinciden");
                        System.out.println(usuario+" Error usuario o contraseña no coincide");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error, usuario o contraseña no coinciden");
                    System.out.println(usuario+" Error usuario o contraseña no coincide");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El password contiene caracteres invalidos");
                System.out.println(usuario+" Error contraseña con caracteres invalidos");
            }
        } catch (SQLException ex) {
            System.out.println("Error de SQL " + ex.getMessage());
            
        }
    }//GEN-LAST:event_jbtIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jbContraseña;
    private javax.swing.JLabel jblContraseña;
    private javax.swing.JLabel jblSesuon;
    private javax.swing.JLabel jblUsuario;
    private javax.swing.JButton jbtIngresar;
    private javax.swing.JButton jbtRegistrarse;
    private javax.swing.JCheckBox jcEmpleado;
    private javax.swing.JTextField jtxContraseña;
    private javax.swing.JTextField jtxUsuario;
    // End of variables declaration//GEN-END:variables
}
